In [1]:
import pandas as pd
import numpy as np
import os
from scipy.stats import variation

In [6]:
for k in range(1,2):   #number of variation or trial....WData_v1, v2
    for j in range(1,8):  #number of word in each variation
        #DATA_PATH="./WData_v"+str(k)+"/Formant/Formant"+str(j)+"/"
        #DATA_PATH="./WData_all/Formant/Formant"+str(j)+"/"
        DATA_PATH="./Vowel_Data/Formant/Formant"+str(j)+"/"
        #DATA_PATH="./Word_Data/Formant/Formant"+str(j)+"/"
        i=0
        for speechfile in os.listdir(DATA_PATH):  #accessing each formant file
            data = pd.read_csv(DATA_PATH+speechfile, delim_whitespace=True,header=None,names=["time","F1","F2","F3","F4","F5"],dtype=np.float64,na_values="--undefined--")
            if i==0:
                cov=variation(data,axis=0)  #row to row variation
                i=1;
            else:
                cov=np.vstack((cov,variation(data,axis=0)))
    
        mean_variation=cov.mean(axis=0)  #row to row mean...mean for all F1, mean for all F2...
    
        #np.save('./New_without_CNN/Formant_variation/COV_trial'+str(k)+'_vowel_'+str(j)+'.npy',mean_variation) #file saved as ....<trial_number>...<word_number>
        #np.save('./Result/COV/COV_all_word_'+str(j)+'.npy',mean_variation) #file saved as ....<trial_number>...<word_number>


In [7]:
mean_variation

array([0.50647537, 0.39146175, 0.4938618 , 0.13122308, 0.06216533,
       0.07009489])

In [4]:
DATA_PATH_w="./Word_Data/Formant/Formant"+str(j)+"/"

array([0.50988726, 0.53342787, 0.41572811, 0.17538039, 0.11974406,
       0.09321043])

In [8]:
np.load('./Result/COV/COV_all_word_7.npy')

array([0.18804143, 0.16094586, 0.13442615, 0.0566681 , 0.04529129,
       0.05310488])

In [4]:
variation_df=pd.DataFrame(np.load('./Result/COV/COV_all_word_7.npy'))

In [5]:
variation_df

0
0  0.188041
1  0.160946
2  0.134426
3  0.056668
4  0.045291
5  0.053105